### ISSUE TITLE
Example can't pass build with version 0.3.2

### ISSUE THREAD

**Issue by JulianZhang** [TOETOE55/lens-rs#6]
rust version is  `rustc 1.57.0 (f1edd0429 2021-11-29)`
With example as blow

```use lens_rs::*;

#[derive(Copy, Clone, Debug, Review, Prism)]
enum Either<L, R> {
    #[optic]
    Left(L), // generate optics::Left
    #[optic]
    Right(R), // generate optics::Right
}

#[derive(Copy, Clone, Debug, Lens)]
struct Tuple<A, B>(#[optic] A, #[optic] B); 
// use optics::_0 or optics::_1 to access it

#[derive(Copy, Clone, Debug, Lens)]
struct Foo<A, B> {
    #[optic]
    a: A, // generate optics::a
    #[optic]
    b: B, // generate optics::b
}


#[derive(Clone, Debug, Lens)]
struct Bar {
    #[optic]
    a: String, // generate optics::a, same as above
    #[optic]
    c: i32,    // generate optics::c
}```

get error 

```error[E0412]: cannot find type `Left` in module `lens_rs::optics`
  --> src/domain/mod.rs:15:5
   |
15 |     Left(L), // generate optics::Left
   |     ^^^^ not found in `lens_rs::optics`
   |
help: there is an enum variant `core::fmt::Alignment::Left` and 11 others; try using the variant's enum
   |
12 | #[derive(Copy, Clone, Debug, core::fmt::Alignment, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, core::fmt::rt::v1::Alignment, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, crate::domain::Either, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, futures::future::Either, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~~~~
     and 7 other candidates

error[E0412]: cannot find type `Right` in module `lens_rs::optics`
  --> src/domain/mod.rs:17:5
   |
17 |     Right(R), // generate optics::Right
   |     ^^^^^ not found in `lens_rs::optics`
   |
help: there is an enum variant `core::fmt::Alignment::Right` and 11 others; try using the variant's enum
   |
12 | #[derive(Copy, Clone, Debug, core::fmt::Alignment, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, core::fmt::rt::v1::Alignment, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, crate::domain::Either, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, futures::future::Either, Prism)]
   |                              ~~~~~~~~~~~~~~~~~~~~~~~
     and 7 other candidates

error[E0412]: cannot find type `Left` in module `lens_rs::optics`
  --> src/domain/mod.rs:15:5
   |
15 |     Left(L), // generate optics::Left
   |     ^^^^ not found in `lens_rs::optics`
   |
help: there is an enum variant `core::fmt::Alignment::Left` and 11 others; try using the variant's enum
   |
12 | #[derive(Copy, Clone, Debug, Review, core::fmt::Alignment)]
   |                                      ~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, Review, core::fmt::rt::v1::Alignment)]
   |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, Review, crate::domain::Either)]
   |                                      ~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, Review, futures::future::Either)]
   |                                      ~~~~~~~~~~~~~~~~~~~~~~~
     and 7 other candidates

error[E0412]: cannot find type `Right` in module `lens_rs::optics`
  --> src/domain/mod.rs:17:5
   |
17 |     Right(R), // generate optics::Right
   |     ^^^^^ not found in `lens_rs::optics`
   |
help: there is an enum variant `core::fmt::Alignment::Right` and 11 others; try using the variant's enum
   |
12 | #[derive(Copy, Clone, Debug, Review, core::fmt::Alignment)]
   |                                      ~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, Review, core::fmt::rt::v1::Alignment)]
   |                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, Review, crate::domain::Either)]
   |                                      ~~~~~~~~~~~~~~~~~~~~~
12 | #[derive(Copy, Clone, Debug, Review, futures::future::Either)]
   |                                      ~~~~~~~~~~~~~~~~~~~~~~~
     and 7 other candidates

error[E0412]: cannot find type `a` in module `lens_rs::optics`
  --> src/domain/mod.rs:27:5
   |
27 |     a: A, // generate optics::a
   |     ^ not found in `lens_rs::optics`

error[E0412]: cannot find type `b` in module `lens_rs::optics`
  --> src/domain/mod.rs:29:5
   |
29 |     b: B, // generate optics::b
   |     ^ not found in `lens_rs::optics`

error[E0412]: cannot find type `a` in module `lens_rs::optics`
  --> src/domain/mod.rs:36:5
   |
36 |     a: String, // generate optics::a, same as above
   |     ^ not found in `lens_rs::optics`

error[E0412]: cannot find type `c` in module `lens_rs::optics`
  --> src/domain/mod.rs:38:5
   |
38 |     c: i32,    // generate optics::c
   |     ^ not found in `lens_rs::optics`

warning: unused import: `ChildStdin`
 --> src/domain/command.rs:3:34
  |
3 | use std::process::{Stdio,Command,ChildStdin};
  |                                  ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `super::validate::validate_raw`
 --> src/domain/model.rs:9:5
  |
9 | use super::validate::validate_raw;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0207]: the type parameter `__Rv` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:12:30
   |
12 | #[derive(Copy, Clone, Debug, Review, Prism)]
   |                              ^^^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Review` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Tr` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:12:38
   |
12 | #[derive(Copy, Clone, Debug, Review, Prism)]
   |                                      ^^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Prism` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Pm` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:12:38
   |
12 | #[derive(Copy, Clone, Debug, Review, Prism)]
   |                                      ^^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Prism` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Tr` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:24:30
   |
24 | #[derive(Copy, Clone, Debug, Lens)]
   |                              ^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Lens` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Pm` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:24:30
   |
24 | #[derive(Copy, Clone, Debug, Lens)]
   |                              ^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Lens` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Ls` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:24:30
   |
24 | #[derive(Copy, Clone, Debug, Lens)]
   |                              ^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Lens` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Tr` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:33:24
   |
33 | #[derive(Clone, Debug, Lens)]
   |                        ^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Lens` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Pm` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:33:24
   |
33 | #[derive(Clone, Debug, Lens)]
   |                        ^^^^ unconstrained type parameter
   |
   = note: this error originates in the derive macro `Lens` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0207]: the type parameter `__Ls` is not constrained by the impl trait, self type, or predicates
  --> src/domain/mod.rs:33:24
   |
33 | #[derive(Clone, Debug, Lens)]
   |                        ^^^^ unconstrained type parameter
```

Can you please give a example project can pass build.

**Comment by TOETOE55** [comment]
Have you added the follow in your `Cargo.toml`?

```toml
[package.metadata.inwelling]
lens-rs_generator = true
```

**Comment by JulianZhang** [comment]
> Have you added the follow in your `Cargo.toml`?
> 
> ```toml
> [package.metadata.inwelling]
> lens-rs_generator = true
> ```

You are right, I miss it , thanks.

**Comment by JulianZhang** [comment]
> Have you added the follow in your `Cargo.toml`?
> 
> ```toml
> [package.metadata.inwelling]
> lens-rs_generator = true
> ```

You are right, I miss it , thanks.
